config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
 get '/search' => 'own_books#search', :as => 'search_own_book'

  resources :contacts, only: [:create, :new]
  authenticated :user do
    root 'own_books#index', as: :authenticated_root
  end
  root "static_pages#index"

  get 'static_pages/team'
  get 'static_pages/privacypolicy'
  #get '/own_books/:id', to: 'own_books#set_available', as: 'switch_availability'
  resources :private_addresses
  resources :cities
  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  resources :own_books do
    patch :set_available
    resources :loans
  end

  resources :loans, only: [:patch] do 
    patch :make_it_past
  end





  resources :books
  devise_for :users, controllers: { registrations: "users/registrations"  }
  resources :users do
    resources :avatars, only: [:create]
  end

end

app/models/own_book.rb
class OwnBook < ApplicationRecord
  belongs_to :user
  belongs_to :book

  has_many :loans


  def loan_request?
    loans.any? == true ? loans.last.is_accepted == false : false
  end

  def current_loan
    loans.last
  end

  def is_loan_past?
    loans.any? == true ? loans.last.is_past : false
  end

  def loaned?
    if loans.any?
      last_loan = loans.last
      last_loan.is_accepted == true && last_loan.is_past == false
    else
      false
    end
  end


  def borrowed_by
    loans.last.borrower
  end

  def self.search(search)  
   where("lower(books.title) LIKE :search OR 
          lower(books.authors) LIKE :search OR 
          lower(users.name) LIKE :search", search: "%#{search.downcase}%").uniq  
  end

end

app/controllers/own_books_controller.rb
class OwnBooksController < ApplicationController
  before_action :set_own_book, only: %i[show edit update destroy ]
  before_action :authenticate_user!


  # GET /own_books or /own_books.json
  def index
    @own_books = OwnBook.all.order('created_at DESC')
    @user = current_user
    @book = Book.all
  end

  def search  
    if params[:search].blank?  
      redirect_to(root_path, notice: "Il faut taper quelque chose dans la barre de recherche !") and return  
    else
     @own_books = OwnBook.joins(:book, :user).search(params[:search])
   end  
 end

  # GET /own_books/1 or /own_books/1.json
  def show
    @book = @own_book.book
  end

  # GET /own_books/new
  def new
    @own_book = OwnBook.new
  end

  # GET /own_books/1/edit
  def edit
  end

  # POST /own_books or /own_books.json
  def create

    @own_book = OwnBook.new(own_book_params)

    respond_to do |format|
      if @own_book.save
        format.html { redirect_to @own_book, notice: "Votre avis a bien été enregistré." }
        format.json { render :show, status: :created, location: @own_book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @own_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /own_books/1 or /own_books/1.json
  def update
    respond_to do |format|
      if @own_book.update(own_book_params)
        format.html { redirect_to @own_book, notice: "Votre avis a bien été mis à jour." }
        format.json { render :show, status: :ok, location: @own_book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @own_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /own_books/1 or /own_books/1.json
  def destroy
    @user = @own_book.user 
    @own_book.destroy
    redirect_to @user
  end

  def set_available
    @own_book = OwnBook.find(params[:own_book_id])
    @own_book.available == true ? @own_book.update(available: false) : @own_book.update(available: true)
    redirect_back(fallback_location: root_path)
  end
  def own_books_in_loan_request
    Loans.find_by()
  end

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_own_book
      @own_book = OwnBook.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def own_book_params
      params.require(:own_book).permit(:review, :appreciation, :genre, :search)
    end
  end

app/helpers/own_books_helper.rb
module OwnBooksHelper
  def current_user_book?(own_book)
    own_book.user == current_user
  end

  def borrowed_by_current_user?(own_book)
    own_book.loaned.borrower == current_user
  end
end

app/views/own_books/_current_user_book_buttons.html.erb
<% if own_book.available %> 

  <%= link_to "Rendre indisponible", 
    own_book_set_available_path(own_book.id), 
    method: :patch, class: "button button-danger" %>

<% elsif own_book.loan_request? %>

  <%= link_to "Accepter la demande d'emprunt de #{own_book.borrowed_by.name}", 
    own_book_loan_path(own_book_id: own_book.id, id: own_book.current_loan.id), 
    method: :patch, class: "button button-success"%>

  <%= link_to "Rejeter la demande d'emprunt de #{own_book.borrowed_by.name}", 
    own_book_loan_path(own_book_id: own_book.id, id: own_book.current_loan.id), 
    method: :delete, class:"button button-primary"%>

<% elsif own_book.is_loan_past? %>

  <%= link_to "Récupérer ?", 
      own_book_set_available_path(own_book.id), 
      method: :patch, class: "button button-success" %> 

<% elsif own_book.loan_request? == false && own_book.loaned? == false %>

  <%= link_to "Rendre disponible", 
    own_book_set_available_path(own_book.id), 
    method: :patch, class: "button button-success" %>

<% else %>

  <button disabled class="button-success"> 
    Préter a <%= own_book.borrowed_by.name %> 
  </button>

<% end %>

app/views/own_books/_current_user_book_buttons_show_page.html.erb
<%= link_to 'donner mon avis', edit_own_book_path(own_book), class:"button button-primary" %>
<% if own_book.loaned? == false && own_book.loan_request? == false %>
  <%= link_to 'Editer les données du livre', edit_book_path(own_book.book), class:"button button-success" %>

  <%= link_to 'supprimer le livre', own_book, method: :delete, data: { confirm: 'Are you sure?' }, class:"button button-danger" %>
<% end %>

app/views/own_books/_currentuserbooks.html.erb
<div class="book-container">
  <div class="nine columns" >
    <div class="card card-list">
      <%if current_user.id != @user.id%>
      <h2 class="text-upp u-text-center">La Bibliothéque de <%= @user.name%>
        <%else%>
        <h2 class="text-upp u-text-center">Votre bibliothéque</h2>
        <%end%>
        <hr>
        <% @own_books.each do |own_book| %>
        <% if own_book.book.image_link != nil %>
        <%= image_tag own_book.book.image_link, class:"book-img-list u-pull-left"%>
        <%else%>
        <%= image_tag "https://res.cloudinary.com/dcmcouvju/image/upload/v1624045770/nocover2_o33zpf.jpg", class:"book-img-list u-pull-left"%>
        <%end%>

        <h6><%=own_book.book.title %></h6>
        <p><%= own_book.book.authors%></p>
        <p><%= own_book.book.isbn%></p> 
        <p><%= own_book.book.description%></p>

        <%= link_to "Fiche du livre", own_book_path(own_book.id), class:"button" %>
        <% if current_user != @user %>
        <% if own_book.loaned? %>
        <button disabled class="button-info"> Déjà Emprunté 😫</button>
        <% elsif own_book.available == false %>
        <button disabled class="button-success"> Temporairement indisponible </button>
        <% else %>
        <%= link_to "Emprunter", own_book_loans_path(own_book.id), method: :create, class:"button button-primary"%>
        <% end %>

        <% else %>

        <% if own_book.available %>

        <%= link_to 'supprimer', own_book, method: :delete, data: { confirm: "En êtes-vous sûr.e ? Celui-ci n'apparaîtra plus dans votre bibliothèque." }, class:"button button-success" %>
        <%= link_to "Rendre indisponible", own_book_set_available_path(own_book.id), method: :patch, class: "button button-danger" %>

        <% else %>

        <% if own_book.loan_request? %>


        <%= link_to "Accepter la demande d'emprunt de #{own_book.loan_request.borrower.name}",  own_book_loan_path(own_book_id: own_book.id, id: own_book.loan_request.id), method: :patch, class: "button button-success"%>

        <%= link_to "Rejeter la demande d'emprunt de #{own_book.loan_request.borrower.name}", own_book_loan_path(own_book_id: own_book.id, id: own_book.loan_request.id),method: :delete, class:"button button-primary"%>

        <% elsif own_book.loaned? %>

        <%= link_to "Prêté à #{own_book.borrowed_by.name}", user_path(own_book.borrowed_by.id) , class: "button button-success"%>

        <%= link_to "#{own_book.borrowed_by.name} m'a bien rendu.e mon livre", own_book_loan_path(own_book_id: own_book.id, id: own_book.loaned.id),method: :delete, class:"button button-primary"%>
       
        <% else %>
        
        <%= link_to 'supprimer', own_book, method: :delete, data: { confirm: "En êtes-vous sûr.e ? Celui-ci n'apparaîtra plus dans votre bibliothèque." }, class:"button button-success" %>

        <%= link_to "Rendre disponible", own_book_set_available_path(own_book.id), method: :patch, class: "button button-primary" %>
        <% end %>

        <% end %>

        <% end %>
        <hr class="hr-index">
        <% end %>
        
        
      </div>
    </div>
  </div>
</div>

app/views/own_books/_form.html.erb
<div class="row">
       <div class="three column"></div>
      <div class="six columns">
          <h2 class="u-text-center text-info text-upp">Donnez votre avis</h2>
          <hr>
<%= form_with(model: own_book, local: true) do |form| %>
  <% if own_book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(own_book.errors.count, "error") %> prohibited this own_book from being saved:</h2>

      <ul>
      <% own_book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Critique", class:"text-dark text-upp" %>
    <%= form.text_area :review, autofocus: true, class: "u-full-width placeholder"%>
  </div>


  <div class="field">
  <%= form.label "Type", class:"text-dark text-upp" %>
  <%= form.select :genre, ["", "Bande Dessinée", "Enfant", "Essai", "Fiction", "Historique", "Loisir", "Philosophie"]%>
  </div>


<fieldset>
  <div class="field inline">
    <%= form.label "Note", class:"text-dark text-upp u-full-width" %>
     <%= form.radio_button :appreciation, '0'  %>
    <%= form.label :appreciation, value:"0"%>
    <%= form.radio_button :appreciation, '1'  %>
    <%= form.label :appreciation, value:"1"%>
    <%= form.radio_button :appreciation, '2' %>
    <%= form.label :appreciation, value:"2"%>    
    <%= form.radio_button :appreciation, '3' %>
    <%= form.label :appreciation, value:"3"%>
    <%= form.radio_button :appreciation, '4' %>
    <%= form.label :appreciation, value:"4"%>
    <%= form.radio_button :appreciation, '5' %>
    <%= form.label :appreciaition, value:"5"%>
  </div>
</fieldset>


  <div class="actions">
    <%= form.submit "soumettre mon avis", class:"button button-primary u-full-width" %>
  </div>
<% end %>
      </div>
      </div>

app/views/own_books/_indexownbook.html.erb
<%i=0%>

<div class="row">
  <div class="six columns"></div>
  <div class="three columns">
    <select id="GetChoice" class="select-text">
      <option >&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp 
        Trier par style de lecture &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      </option>
      <option >Bande Dessinée</option>
      <option >Enfant</option>
      <option >Essai</option>
      <option >Fiction</option>
      <option >Historique</option>
      <option >Loisir</option>
      <option >Philosophie</option>
    </select>
  </div>
  <div class="three columns">
    <input type="button", value="trier" onclick="GetSelectedTextValue()" class="button button-select-genre" />
  </div>
</div>
<br>  

<div class="container">
  <% @own_books.each do |own_book|%>



  <div id = "<%=own_book.genre%>" class="genre-select" >
    <div class="row">
      <div class="card card-list">
        <div class="five columns">

          <% if own_book.book.image_link != nil %>
          <%= link_to image_tag(own_book.book.image_link), own_book, class:"book-img-list"%>
          <div class="one column"></div>
          <%else%>
          <%= image_tag "https://res.cloudinary.com/dcmcouvju/image/upload/v1624045770/nocover2_o33zpf.jpg", class:"book-img-list"%>
          <%end%>
        </div>
        <div class="six columns">
          <h6 class="text-upp text-dark"><%=own_book.book.title %></h6>
          <p>Auteur : <%=own_book.book.authors%></p>
          <p>Catégorie : <%=own_book.genre %></p>
          <br>
          <p>Propriétaire du livre : <%=own_book.user.name%> <br> Ville : <%=own_book.user.private_address.try(:city).try(:name)%> </p>



          <%= link_to "Plus d'infos", own_book, class:"button button-primary"%>



          <!-- Trigger/Open The Modal -->
          <button id = "<%=i%>" class="btntrig button button-success" onclick="OpenModal()">Fiche du Livre</button>
          
          <!-- The Modal -->
          <div id = "<%=i%>" class="modal">
            
            <!-- Modal content -->
            <div class="modal-content">
              <span id="<%=i%>" class="close">&times;</span>


              <p id="notice"><%= notice %></p>

              <% empty = '-'%>
              
              <h2 class="text-upp u-text-center"><%= own_book.book.title %></h2>
              
              <div class="row">
                <div class="container">
                  <hr>
                  <div class="six columns">
                    <%= image_tag own_book.book.image_link%>
                    <p>
                      <strong class="text-dark text-upp">ISBN :</strong>
                      <%= (own_book.book.isbn != '' ? own_book.book.isbn : empty) %>
                    </p>
                    <p>
                      <strong class="text-dark text-upp">Auteur.e.s :</strong>
                      <%= (own_book.book.authors != '' ? own_book.book.authors : empty) %>
                    </p>
                    
                    <p>
                      <strong class="text-dark text-upp">Editions :</strong>
                      <%= (own_book.book.publisher != '' ? own_book.book.publisher : empty) %>
                    </p>
                  </div>
                  <p>
                    <strong class="text-dark text-upp">Date de publication :</strong>
                    <%= (own_book.book.published_date != '' ? own_book.book.published_date : empty) %>
                  </p>
                  
                  <p>
                    <strong class="text-dark text-upp">Langue :</strong>
                    <%= (own_book.book.language != '' ? own_book.book.language : empty) %>
                  </p>
                  
                  
                  
                  <p>
                    <strong class="text-dark text-upp">Résumé :</strong>
                    <%= (own_book.book.description != '' ? own_book.book.description : empty) %>
                  </p>
                  <p>
                    <strong class="text-dark text-upp">Critique :</strong>
                    <%= own_book.review %>
                  </p>
                  <hr>
                  <p>
                    <strong class="text-dark text-upp">Catégorie :</strong>
                    <%= own_book.genre %>
                  </p>
                  
                  
                  
                  <p>
                    <strong class="text-dark text-upp">Note :</strong>
                    <%= own_book.appreciation %>/5
                  </p>
                  
                  <p>
                    <strong class="text-dark text-upp">Propriétaire du livre :</strong>
                    <%= link_to own_book.user.name, user_path(own_book.user_id), class:"text-info" %>
                  </p>
                  <%= link_to "Plus d'infos", own_book, class:"button button-primary u-pull-right"%>
                </div>
                
              </div>
              
            </div>
          </div>
          <hr class="hr-index">
        </div>
      </div>
    </div>
  </div>
  <%i+=1%>
  <%end%>
</div>
</div>
</div>

app/views/own_books/_other_user_book_buttons.html.erb
<% if own_book.available %>

  <%= link_to "Emprunter", 
               own_book_loans_path(own_book.id), 
               method: :create, class:"button button-success" %>

<% elsif own_book.loaned?%>

  <% if own_book.borrowed_by == current_user %>

    <%= link_to "Le rendre a son propriétaire", 
        loan_make_it_past_path(loan_id: own_book.current_loan.id), 
        method: 'patch', class: "first-button button button-success u-full-width" %>

  <% else %>

    <button disabled class="button-success"> déjà emprunté </button>

  <% end %>

<% elsif own_book.is_loan_past? %>

  <button disabled class="button-success"> Bientôt disponible </button>

<% else %>

  <button disabled class="button-success"> Temporairement indisponible </button>

<% end %>

app/views/own_books/_own_book.html.erb
<div id = "<%=own_book.genre%>" class="genre-select" >
  <div class="row">
    <div class="card card-list">
      <div class="five columns">

        <% if own_book.book.image_link != nil %>

          <%= link_to image_tag(own_book.book.image_link), 
              own_book, class:"book-img-list"%>

        <%else%>

          <%= image_tag "https://res.cloudinary.com/dcmcouvju/image/upload/v1624045770/nocover2_o33zpf.jpg", class:"book-img-list"%>

        <%end%>

      </div>

      <div class="seven columns">
        <h6 class="text-upp text-dark"><%=own_book.book.title %></h6>

        <p>Auteur : <%=own_book.book.authors%></p>
        <p>Catégorie : <%=own_book.genre%></p> <br>
        <p>Propriétaire du livre : <%=own_book.user.name%> <br> 
           Ville : <%=own_book.user.private_address.try(:city).try(:name)%> </p>

        <%= link_to "Fiche du Livre", own_book, class:"button"%>

        <% if current_user_book?(own_book) %>

          <%= render "current_user_book_buttons", own_book: own_book %>

        <% else %>

          <%= link_to "Prêteur", user_path(own_book.user_id), class:"button button-primary"%>
          <%= render "other_user_book_buttons", own_book: own_book %>

        <% end %>
      </div>
    </div>
  </div>
  <hr class="hr-index">
</div>

app/views/own_books/edit.html.erb
<%= render 'form', own_book: @own_book %>
<%= link_to 'Retour à la fiche du livre', @own_book, class:"button button-success" %>
<%= link_to "Profil de l'utilisateur", user_path(current_user.id), class:"button u-pull-right" %>

app/views/own_books/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <br>
  <div class="row">
    <div class="six columns">
      <%= link_to 'Ajouter un livre à ma bibliothèque', new_book_path, class:"button button-success" %>
    </div>
    <div class="three columns">
      <%= form_tag(search_own_book_path, :method => "get") do %>  
      <div class="input-group">  
        <%= search_field_tag :search, params[:search], placeholder: "Chercher un titre, un profil", class: "u-full-width" %>
      </div>
    </div>
    <div class="three columns">
      <div class="input-group-btn">  
        <%= button_tag "rechercher", :class => 'button button-primary',:name => nil%>  
      </div>  
    </div>  
    <% end %>
  </div>
</div>
<h2 class="text-upp u-text-center">Tous les livres</h2>

<div class="container">
 <hr class="hr-index">  
 <%= render "indexownbook"%>
</div>

app/views/own_books/new.html.erb
<h1>Laisser un avis sur mon livre</h1>



<%= render 'form', own_book: @own_book %>

<%= link_to 'Back', own_books_path %>

app/views/own_books/search.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <br>
  <div class="row">
    <div class="six columns">
      <%= link_to 'Ajouter un livre à ma bibliothèque', new_book_path, class:"button button-success" %>
    </div>
    <div class="three columns">
      <%= form_tag(search_own_book_path, :method => "get") do %>  
      <div class="input-group">  
        <%= search_field_tag :search, params[:search], placeholder: "Chercher un titre, un profil", class: "u-full-width" %>
      </div>
    </div>
    <div class="three columns">
      <div class="input-group-btn">  
        <%= button_tag "rechercher", :class => 'button button-primary',:name => nil%>  
      </div>  
    </div>  
    <% end %>
  </div>
</div>
<h2 class="text-upp u-text-center">Résultat de la recherche</h2> 
<div class="container">
 <hr class="hr-index">
 <%= render "indexownbook"%>
</div>

app/views/own_books/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <% empty = '-'%>

  <h2 class="text-upp u-text-center"><%= @book.title %></h2>

  <div class="row">

    <hr>
    <div class="six columns">
      <%= image_tag @book.image_link%>
      <p>
        <strong class="text-dark text-upp">ISBN :</strong>
        <%= (@book.isbn != '' ? @book.isbn : empty) %>
      </p>
      <p>
        <strong class="text-dark text-upp">Auteur.e.s :</strong>
        <%= (@book.authors != '' ? @book.authors : empty) %>
      </p>

      <p>
        <strong class="text-dark text-upp">Editions :</strong>
        <%= (@book.publisher != '' ? @book.publisher : empty) %>
      </p>
    </div>
    <p>
      <strong class="text-dark text-upp">Date de publication :</strong>
      <%= (@book.published_date != '' ? @book.published_date : empty) %>
    </p>

    <p>
      <strong class="text-dark text-upp">Langue :</strong>
      <%= (@book.language != '' ? @book.language : empty) %>
    </p>



    <p>
      <strong class="text-dark text-upp">Résumé :</strong>
      <%= (@book.description != '' ? @book.description : empty) %>
    </p>
    <hr>
    <p>
      <strong class="text-dark text-upp">Critique :</strong>
      <%= @own_book.review %>
    </p>
    
    <p>
      <strong class="text-dark text-upp">Catégorie :</strong>
      <%= @own_book.genre %>
    </p>



    <p>
      <strong class="text-dark text-upp">Note :</strong>
      <%= @own_book.appreciation %>/5
    </p>

    <p>
      <strong class="text-dark text-upp">Propriétaire du livre :</strong>
      <%= link_to @own_book.user.name, user_path(@own_book.user_id), class:"text-info" %>
    </p>

  </div>

</div>

<div class="container">
  <br>
  <%= link_to 'Tous les livres', own_books_path, class:"button" %>
  <% if current_user != @own_book.user %>
  <% if @own_book.loan_request? %>
  <button disabled class="button-success"> Temporairement indisponible </button>
  <% elsif !@own_book.loaned.nil? && @own_book.loaned.borrower == current_user%>
  <%= link_to "Le rendre a son propriétaire", "", class: "button button-success" %> 
  <% else %>
  <%= link_to "Emprunter le livre", own_book_loans_path(@own_book.id), method: :create, class:"button button-primary"%>
  <% end %>
  <% else %>
  <%= link_to 'donner mon avis', edit_own_book_path(@own_book), class:"button button-primary" %>
  <% if @own_book.loaned? == false && @own_book.loan_request? == false %>
  <%= link_to 'Editer les données du livre', edit_book_path(@own_book.book), class:"button button-success" %>

  <%= link_to 'supprimer le livre', @own_book, method: :delete, data: { confirm: 'En êtes vous sûr.e ?!' }, class:"button button-danger" %>
  <% end %>
  <% end %>
</div>