config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
 get '/search' => 'own_books#search', :as => 'search_own_book'

  resources :contacts, only: [:create, :new]
  authenticated :user do
    root 'own_books#index', as: :authenticated_root
  end
  root "static_pages#index"

  get 'static_pages/team'
  get 'static_pages/privacypolicy'
  #get '/own_books/:id', to: 'own_books#set_available', as: 'switch_availability'
  resources :private_addresses
  resources :cities
  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  resources :own_books do
    patch :set_available
    resources :loans
  end

  resources :loans, only: [:patch] do 
    patch :make_it_past
  end





  resources :books
  devise_for :users, controllers: { registrations: "users/registrations"  }
  resources :users do
    resources :avatars, only: [:create]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send

  has_one_attached :avatar

  has_many :messages
  has_many :conversations, foreign_key: :sender_id
  has_many :lenders, foreign_key: 'lender_id', class_name: "Loan"
  has_many :borrowers, foreign_key: 'borrower_id', class_name: "Loan"

  has_many :loans
  has_many :own_books
  has_many :books, through: :own_books

  belongs_to :private_address, dependent: :destroy, optional: true

  accepts_nested_attributes_for :private_address


  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  #  def after_sign_up_path_for(resource_or_scope)
  #      puts current_user
  #      redirect_to edit_registration_path(current_user.id)
  #      #user_edit_path(current_user)
  #  end

  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end
  #

  protected

  def after_sign_up_path_for(resource)
    edit_user_path(current_user.id)
  end

  def after_inactive_sign_up_path_for(resource)
    edit_user_path(current_user.id)
  end


  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find(params[:id])
    if @user != current_user
      @own_books = @user.own_books.order('created_at DESC')
    else
      @own_books = @user.own_books
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "Bienvenue ! Commence sans plus attendre à ajouter tes livres !" }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    puts "\n" * 50
    puts user_params
    @city = City.find_by(name: user_params[:city])
    if @city.nil?
      @city = City.create(name: user_params[:city], zip_code: user_params[:zip_code])
    end
    puts "\n" * 50
    puts "USER = #{user_params[:street_name]}   OTHER_INFO == #{user_params[:other_information]}"
    @private_address = PrivateAddress.create(street_name: user_params[:street_name], other_information: user_params[:other_information], city: @city, user: @user)
    @private_address.errors
      

    respond_to do |format|
      if @user.update(name: user_params[:name], biography: user_params[:biography], private_address: @private_address)
        format.html { redirect_to @user, notice: "Les modifications sont bien enregistrées." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy

    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "Votre compte est bien détruit." }
      format.json { head :no_content }
    end
  end

#  def books_in_loan_request
#    @books_in_loan_request = []
#    @user.borrowers.each { |loan| @borrowed_books << loan.own_book if loan.is_past == false && loan.accepted == false }
#  end
#
#  def borrowed_books
#    @borrowed_books = []
#    @user.borrowers.each { |loan| @borrowed_books << loan.own_book if loan.is_past == false && loan.accepted }
#  end
#
#  def loaned_books
#    @loaned_books = []
#    @user.lenders.each { |loan| @loaned_books << loan.own_book if loan.is_past == false && loan.accepted }
#  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :biography, :city, :zip_code, :street_name, :other_information)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">

  <div class="three column"></div>
  <div class="six columns">
    <hr>
  <div class="field">
    <%= form.label "Identité", class:"text-dark text-upp" %>
    <%= form.text_field :name, placeholder:"Ton doux prénom et ton nom de famille si tu le souhaites", class: "u-full-width placeholder" %>
  </div>

  <div class="field">
    <%= form.label "Description", class:"text-dark text-upp" %>
    <%= form.text_area :biography, placeholder:"Ecris ici une belle description de ta personne !", class: "u-full-width placeholder", rows:"5" %>
  </div>

  <div class="field">
    <%= form.label "Adresse", class:"text-dark text-upp" %>
    <%= form.text_field :street_name, placeholder:"Indique ton adresse" ,class: "u-full-width placeholder" %>
  </div>

  <div class="field">
    <%= form.label "Code postal", class:"text-dark text-upp" %>
    <%= form.text_field :zip_code, placeholder:"Indique ton code postal", class: "u-full-width placeholder" %>
  </div>
  <div class="field">
    <%= form.label "Ville", class:"text-dark text-upp" %>
    <%= form.text_field :city, placeholder:"Indique ta ville", class: "u-full-width placeholder" %>
  </div>

  
  <div class="field">
    <%= form.label "Informations additionnelles", class:"text-dark text-upp" %>
    <p class="text-dark">(lieu-dit, boite postale, etc...)</p>
    <%= form.text_field :other_information, placeholder:"Une information concernant ton adresse ou un détail que les autres doivent connaitre ? C'est par ici.",class: "u-full-width placeholder" %>
  </div>

  <div class="actions">
    <%= form.submit "Valider les informations", class:"u-full-width button-primary" %>
  </div>
<% end %>
<%= link_to "Retour au profil", @user, class:"button button-success" %>

<%= link_to "Retour à l'index des livres", own_books_path, class:"button u-pull-right" %>
   </div>
  </div>
</div>

app/views/users/_otheruserprofile.html.erb
  <div class="book-container">
  <div class="row">
    <div class="three columns" >
      <div class="card user-profile">
      <%if @user.avatar.attached?%>
      <% image_tag @user.avatar, class:"avatar"%>
      <%else%>
        <div class="avatar"></div>
        <%end%>
        <div class="buttons">
        <%= mail_to @user.email, "Contacter" ,class:"first-button button button-success u-full-width"%></div>
        <hr class="hr-index">
        <h6 class="username text-dark"><%= @user.name%></h6>
        <p class="user-description text-dark"><%= @user.biography %></p>
      <hr class="hr-index">
        <%if @user.private_address == nil %>

        <%else%>
        <p class="text-upp u-text-center text-dark"><%= @user.private_address.street_name%></p>
<p class="text-upp u-text-center text-dark text-bold"><%= link_to @user.private_address.city.name ,"https://www.google.fr/maps/place/#{@user.private_address.street_name + "+" +@user.private_address.city.name}", class:"city-link", :target => "_blank" %></p>        <%end%>
      <hr>
      </div>
      </div>

app/views/users/_userprofile.html.erb
<div class="book-container">
  <div class="row">
    <div class="three columns" >
      <div class="card user-profile">
        <%if @user.avatar.attached?%>
        <%= image_tag @user.avatar, class:"avatar u-full-width"%>
        <%else%>
        <div class="avatar">
        </div>
        <%end%>
        <div class="buttons">
          <%= form_tag user_avatars_path(@user), multipart: true do %>
          <%= file_field_tag :avatar, class:"u-full-width button custom-file-input" %>
          <%= submit_tag "valider l'avatar", class:" first-button button button-info u-full-width"%>
          <%=link_to "Ajouter un livre", new_book_path, class:"button button-primary u-full-width"%>
          <%=link_to "Les Prêts", own_book_loans_path(@current_user.id), class:"button button-info-full u-full-width"%>
          <%=link_to "Editer le profil", edit_user_path, class:"button button-success u-full-width"%>
        </div>
        <%end%>
        
        <hr class="hr-index">
        <h6 class="username text-dark"><%=@user.name%></h6>
        <p class="user-description text-dark"><%= @user.biography %></p>
        <hr class="hr-index">
        <%if @user.private_address == nil %>

        <%else%>
        <p class="text-upp u-text-center text-dark"><%= @user.private_address.street_name%></p>
        <p class="text-upp u-text-center text-dark text-bold"><%= link_to @user.private_address.city.name ,"https://www.google.fr/maps/place/#{@user.private_address.street_name + "+" +@user.private_address.city.name}", class:"city-link", :target => "_blank" %></p>
          <%end%>
          <hr>
          <%=link_to "Modifier le compte", edit_user_registration_path, class:"button button-danger u-full-width"%>
        </div>
      </div>

app/views/users/edit.html.erb
<h2 class="u-text-center text-upp">Editer mon profil</h2>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Biography</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.biography %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
</div>
<%if @user.id === current_user.id%>
<%= render "userprofile"%>
<%else%>
<%=render "otheruserprofile"%>
<%end%>
<%= render "own_books/currentuserbooks"%>

app/views/users/show.js.erb
console.log(document.querySelector("a#index-btn")):