config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
 get '/search' => 'own_books#search', :as => 'search_own_book'

  resources :contacts, only: [:create, :new]
  authenticated :user do
    root 'own_books#index', as: :authenticated_root
  end
  root "static_pages#index"

  get 'static_pages/team'
  get 'static_pages/privacypolicy'
  #get '/own_books/:id', to: 'own_books#set_available', as: 'switch_availability'
  resources :private_addresses
  resources :cities
  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  resources :own_books do
    patch :set_available
    resources :loans
  end

  resources :loans, only: [:patch] do 
    patch :make_it_past
  end





  resources :books
  devise_for :users, controllers: { registrations: "users/registrations"  }
  resources :users do
    resources :avatars, only: [:create]
  end

end

app/models/loan.rb
class Loan < ApplicationRecord

  after_create :send_request_to_loan_book
  after_update :send_accepted_request, unless: :is_past?
  after_update :send_book_returned_email, if: :is_past?
  after_destroy :send_declined_request

  belongs_to :lender, class_name: "User"
  belongs_to :borrower, class_name: "User"
  belongs_to :own_book
  
  def is_past?
    is_past
  end

  def send_request_to_loan_book
   UserMailer.ask_owner_to_borrow_his_book(self).deliver_now
   UserMailer.copy_ask_owner_to_borrow_his_book(self).deliver_now
  end

  def send_declined_request
    UserMailer.request_declined(self).deliver_now
  end
  def send_accepted_request
    UserMailer.request_accepted(self).deliver_now
  end
  def send_book_returned_email
    UserMailer.book_returned_email_to_borrower(self).deliver_now
    UserMailer.book_returned_email_to_owner(self).deliver_now
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: %i[ show edit update destroy ]
  before_action :find_own_book, only: %i[create destroy update]
  before_action :authenticate_user!

  # GET /loans or /loans.json
  def index
    @borrowers = Loan.where(borrower: current_user)
    @lenders = Loan.where(lender: current_user)
  end

  # GET /loans/1 or /loans/1.json
  def show
    @loan = @own_book.book
  end

  # GET /loans/new
  def new
    @loan = Loan.new
  end

  # GET /loans/1/edit
  def edit
  end

  # POST /loans or /loans.json
  def create
    @own_book.update(available: false)
    @loan = Loan.new(borrower: current_user, lender: @own_book.user, own_book: @own_book)

    UserMailer.ask_owner_to_borrow_his_book(@own_book, current_user).deliver_now
    UserMailer.copy_ask_owner_to_borrow_his_book(@own_book, current_user).deliver_now


    respond_to do |format|
      if @loan.save
        format.html { redirect_back(fallback_location: root_path, notice: "La demande d'emprunt a été envoyée au propriétaire du livre.") }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render root_path, status: :unprocessable_entity }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1 or /loans/1.json
  def update
    @loan = Loan.find(params[:id])
    UserMailer.request_accepted(@loan).deliver_now
    #redirect_back(fallback_location: root_path)
    respond_to do |format|

      if @loan.update(is_accepted: true)
        format.html { redirect_back(fallback_location: root_path) }

        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { redirect_back(fallback_location: root_path) }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1 or /loans/1.json
  def destroy
    @own_book.update(available: true)
    @loan.destroy
    UserMailer.request_declined(@loan).deliver_now

    respond_to do |format|
      format.html { redirect_back fallback_location: root_path, notice: "La réservation a bien été supprimée." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      puts "PARAMS = #{params}"
      @loan = Loan.find(params[:id])
    end

    def find_own_book
      @own_book = OwnBook.find(params[:own_book_id])
    end

    # Only allow a list of trusted parameters through.
    def loan_params
      params.require(:loan, :own_book_id)
    end
  end

app/helpers/loans_helper.rb
module LoansHelper

  def user_loan?(user)
    Loan.where(borrower: user).nil?
  end

  def user_borrow?(user)
    Loan.where(lender: user).nil?
  end
end

app/views/loans/_currentbooksborrow.html.erb
<div class="row">
  <div class="one columns" ></div>
  <div class="ten columns">
    <div class="card card-loan">
      <h4 class="text-upp text-info u-text-center">Livres qu'on vous emprunte :</h4>
      
      <hr>
      <%if !user_borrow?(current_user) %>
      <% lenders.each do |loan| %>
      <%= link_to "Prêté à #{loan.borrower.name} le #{loan.updated_at}", user_path(loan.borrower.id) , class: "button button-success u-pull-right"%>

      <%= link_to "#{loan.own_book.borrowed_by.name} m'a bien rendu.e mon livre", own_book_loan_path(own_book_id: loan.own_book.id, id: loan.own_book.loaned.id),method: :delete, class:"button button-primary"%>
      <% if loan.own_book.book.image_link.nil? %>
      <%= image_tag "https://res.cloudinary.com/dcmcouvju/image/upload/v1624045770/nocover2_o33zpf.jpg", class:"u-pull-left"%>
      <%else%>

      <%= image_tag loan.own_book.book.image_link, class:"book-img-list u-pull-left"%>
      <%end%>

      <h6><%=loan.own_book.book.title %></h6>
      <p><%= loan.own_book.book.authors%></p>
      <p><%= loan.own_book.book.isbn%></p> 
      <p><%= loan.own_book.book.description%></p>
      <hr>
      <%end%>
    </div>
  </div>
  <%else%>
  <p>Pas d'emprunts</p>
  <%end%>
  <div class="one columns"></div>
</div>

app/views/loans/_currentbooksloan.html.erb
<div class="row">
  <div class="one columns" ></div>
  <div class="ten columns">
    <div class="card card-loan">
      <h4 class="text-upp text-info u-text-center">Livres en votre possession :</h4>
      
      <hr>
      <%if !user_loan?(current_user) %>
      <% borrowers.each do |borrower| %>
      <%= link_to "Prêté par #{borrower.lender.name} le #{borrower.updated_at}", user_path(borrower.lender.id) , class: "button button-success u-pull-right"%>
      <% if borrower.own_book.book.image_link.nil? %>
      <%= image_tag "https://res.cloudinary.com/dcmcouvju/image/upload/v1624045770/nocover2_o33zpf.jpg", class:"u-pull-left"%>
      <%else%>
      
      <%= image_tag borrower.own_book.book.image_link, class:"book-img-list u-pull-left"%>
      <%end%>

      <h6><%=borrower.own_book.book.title %></h6>
      <p><%= borrower.own_book.book.authors%></p>
      <p><%= borrower.own_book.book.isbn%></p> 
      <p><%= borrower.own_book.book.description%></p>
      <hr>
      <%end%>
    </div>
  </div>
  <%else%>
  <p>Pas d'emprunts</p>
  <%end%>
  <div class="one columns"></div>
</div>

app/views/loans/_form.html.erb
<%= form_with(model: loan, local: true) do |form| %>
  <% if loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
      <% loan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/loans/edit.html.erb
<h1>Editing Loan</h1>

<%= render 'form', loan: @loan %>

<%= link_to 'Show', @loan %> |
<%= link_to 'Back', loans_path %>

app/views/loans/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <%= render 'currentbooksloan', borrowers: @borrowers %>
  <%= render 'currentbooksborrow', lenders: @lenders %>
</div>

app/views/loans/new.html.erb
<h1>New Loan</h1>

<%= render 'form', loan: @loan %>

<%= link_to 'Back', loans_path %>

app/views/loans/show.html.erb
<p id="notice"><%= notice %></p>