config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
 get '/search' => 'own_books#search', :as => 'search_own_book'

  resources :contacts, only: [:create, :new]
  authenticated :user do
    root 'own_books#index', as: :authenticated_root
  end
  root "static_pages#index"

  get 'static_pages/team'
  get 'static_pages/privacypolicy'
  #get '/own_books/:id', to: 'own_books#set_available', as: 'switch_availability'
  resources :private_addresses
  resources :cities
  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  resources :own_books do
    patch :set_available
    resources :loans
  end

  resources :loans, only: [:patch] do 
    patch :make_it_past
  end





  resources :books
  devise_for :users, controllers: { registrations: "users/registrations"  }
  resources :users do
    resources :avatars, only: [:create]
  end

end

app/helpers/private_addresses_helper.rb
module PrivateAddressesHelper
end

app/views/private_addresses/_form.html.erb
<%= form_with(model: private_address, local: true) do |form| %>
  <% if private_address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(private_address.errors.count, "error") %> prohibited this private_address from being saved:</h2>

      <ul>
      <% private_address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :street_name %>
    <%= form.text_field :street_name %>
  </div>

  <div class="field">
    <%= form.label :other_information %>
    <%= form.text_field :other_information %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/private_addresses/edit.html.erb
<h1>Editing Private Address</h1>

<%= render 'form', private_address: @private_address %>

<%= link_to 'Show', @private_address %> |
<%= link_to 'Back', private_addresses_path %>

app/views/private_addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Private Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Street name</th>
      <th>Other information</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @private_addresses.each do |private_address| %>
      <tr>
        <td><%= private_address.street_name %></td>
        <td><%= private_address.other_information %></td>
        <td><%= link_to 'Show', private_address %></td>
        <td><%= link_to 'Edit', edit_private_address_path(private_address) %></td>
        <td><%= link_to 'Destroy', private_address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Private Address', new_private_address_path %>

app/views/private_addresses/new.html.erb
<h1>New Private Address</h1>

<%= render 'form', private_address: @private_address %>

<%= link_to 'Back', private_addresses_path %>

app/views/private_addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Street name:</strong>
  <%= @private_address.street_name %>
</p>

<p>
  <strong>Other information:</strong>
  <%= @private_address.other_information %>
</p>

<%= link_to 'Edit', edit_private_address_path(@private_address) %> |
<%= link_to 'Back', private_addresses_path %>